# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
workflows:
  test-env-vars:
    jobs:
      - build:
          context: Keys

jobs:
  build:
    working_directory: ~/Cart-Service
    docker:
      - image: circleci/node:fermium
    environment: $BING_API_KEY
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
          paths:
            - /home/circleci/.npm
      - run:
          name: "What was my custom environment variable?"
          command: echo $BING_API_KEY
      - run:
          name: Run Tests
          command: npm test $BING_API_KEY